### ISSUE TITLE
Transition from libafs.ko to openafs.ko in afsutil

### ISSUE THREAD

**Issue by jhgorse** [openafs-contrib/openafs-robotest#11]
## Proposal: build openafs.ko
1) move from building libafs.ko to openafs.ko 
2) install to /lib/modules/`built uname -r`/kernel/fs/openafs/openafs.ko in addition to 'dest'. Note that we install to the potentially cross-compiled kernel version, not necessarily the current uname -r. I currently do not do cross-compiled AFS builds yet.
3) load/reload from /lib/modules/`uname -r`/kernel/fs/openafs/openafs.ko

Reasoning is that this is where linux expects kernel modules, depmod -a will function and put our .ko in the cache, and because it helps systemtap function properly. Also, the name openafs.ko is slightly more meaningful to the new user than libafs.ko.

## How to do it
1) Add this to the ./configure in the build script: **--with-linux-kernel-packaging**
For completeness, my current configure line is:
```
./configure --with-krb5 --disable-strip-binaries --enable-debug --disable-optimize --enable-debug-kernel --disable-optimize-kernel --enable-debug-lwp --without-dot --enable-checking --enable-transarc-paths --with-linux-kernel-packaging
```
2 & 3) In afsutil's build.py:137, change the linux path to:
```python
def _kmod():
    uname = os.uname()[0]
    kernel = os.uname()[2]
    if uname == 'Linux':
        kmod = os.path.abspath("/lib/modules/%s/kernel/fs/openafs/openafs.ko" % (kernel)) 
```
It may also need some glue to install there, create directory, depmod -a, etc.

Cheers,
Joe

**Comment by meffie** [comment]
A commit was pushed to master to address afsutil install --dist transarc,
and one (or more) are one the way to address afsutil reload.

The --with-linux-kernel-packaging and --enable-transarc-paths don't make a lot
of sense together, because enable-transarc-paths really means, create a
transarc-style tarball distribution, not a package.  They seem contradictory.

However, looking at what --with-linux-kernel-packaging actually does, it would
be better named as "--with-linux-kernel-modern-naming", or some such.  The dest
install targets already support the modern naming style in 
src/libafs/MakefileProto.linux.in.

So there are several fixes that need to be done.

1. afsutil install --dist transarc needs to install the openafs.ko to the
   modern /lib/modules/$(uname -r) path, and then run depmod.  This is done
   now.  (Fortunately, the solaris installer has a similar step, so this
   just meant implementing the linux version of that step.)

2. The init script provided in the transarc-style tarball needs to be updated
   to run modprobe openafs instead of insmod libafs, and handle the remove of
   openafs.ko when it is loaded.  A patch for src/afsd/afs.rc.linux was made
   available in the patches directory until the in-tree version is fixed.

Note that afs.rc.linux is really just an example script, written before linux
2.4, and is what normally used on modern systems. Modern packaging systems
provide their own init scripts.

The change for afsutil reload is in progress.

**Comment by meffie** [comment]
Hello Joe,

I believe this is addressed on the master branch now, for both the install and the 'afsutil reload' command.
The main commits to address this are:

4fbf595 afsutil: reload openafs.ko too
000ebee afsutil: support modern linux kernel naming in init script
fd4c9e3 afsutil: use afsutil init scripts for transarc installs
b036660 afsutil: import init scripts for transarc-style installs
34a4602 afsutil: support modern linux kernel module naming with transarc

Thanks,
Mike

**Comment by meffie** [comment]
afsutil build now defaults to building openafs.ko on linux (on master).

Use the  --no-modern-kmod-name to disable that, and build the kmod with the legacy naming convention libafs-$(uname -r).ko

Thanks,
Mike
